### ISSUE TITLE
用不了

### ISSUE THREAD

**Issue by liuaifu** [binux/pyproxy#2]
环境：win7x64，python3.6.5 x86，tornado5.0.2
在IE中设置http代理访问www.baidu.com报错：

    D:\>python pyproxy.py
    [I 180625 16:57:01 pyproxy:441] http server started on 127.0.0.1:8888
    [E 180625 16:57:05 http1connection:54] Uncaught exception
        Traceback (most recent call last):
          File "C:\Program Files (x86)\Python36-32\lib\site-packages\tornado\http1co
    nnection.py", line 184, in _read_message
            header_future = delegate.headers_received(start_line, headers)
          File "C:\Program Files (x86)\Python36-32\lib\site-packages\tornado\simple_
    httpclient.py", line 458, in headers_received
            self.request.header_callback('%s %s %s\r\n' % first_line)
          File "C:\Program Files (x86)\Python36-32\lib\site-packages\tornado\stack_c
    ontext.py", line 276, in null_wrapper
            return fn(*args, **kwargs)
          File "pyproxy.py", line 252, in <lambda>
            req.header_callback = lambda line, stream=stream: not stream.closed() an
    d stream.write(line) if not line.startswith('Transfer-Encoding') else None
          File "C:\Program Files (x86)\Python36-32\lib\site-packages\tornado\iostrea
    m.py", line 530, in write
            self._write_buffer.append(data)
          File "C:\Program Files (x86)\Python36-32\lib\site-packages\tornado\iostrea
    m.py", line 156, in append
            self._buffers.append((False, bytearray(data)))
        TypeError: string argument without an encoding
    [E 180625 16:57:05 ioloop:792] Exception in callback functools.partial(<function
     wrap.<locals>.wrapped at 0x03968C90>, <Future finished exception=_QuietExceptio
    n()>)
        Traceback (most recent call last):
          File "C:\Program Files (x86)\Python36-32\lib\site-packages\tornado\http1co
    nnection.py", line 184, in _read_message
            header_future = delegate.headers_received(start_line, headers)
          File "C:\Program Files (x86)\Python36-32\lib\site-packages\tornado\simple_
    httpclient.py", line 458, in headers_received
            self.request.header_callback('%s %s %s\r\n' % first_line)
          File "C:\Program Files (x86)\Python36-32\lib\site-packages\tornado\stack_c
    ontext.py", line 276, in null_wrapper
            return fn(*args, **kwargs)
          File "pyproxy.py", line 252, in <lambda>
            req.header_callback = lambda line, stream=stream: not stream.closed() an
    d stream.write(line) if not line.startswith('Transfer-Encoding') else None
          File "C:\Program Files (x86)\Python36-32\lib\site-packages\tornado\iostrea
    m.py", line 530, in write
            self._write_buffer.append(data)
          File "C:\Program Files (x86)\Python36-32\lib\site-packages\tornado\iostrea
    m.py", line 156, in append
            self._buffers.append((False, bytearray(data)))
        TypeError: string argument without an encoding
    
        During handling of the above exception, another exception occurred:
    
        Traceback (most recent call last):
          File "C:\Program Files (x86)\Python36-32\lib\site-packages\tornado\ioloop.
    py", line 759, in _run_callback
            ret = callback()
          File "C:\Program Files (x86)\Python36-32\lib\site-packages\tornado\stack_c
    ontext.py", line 344, in wrapped
            raise_exc_info(exc)
          File "<string>", line 4, in raise_exc_info
          File "C:\Program Files (x86)\Python36-32\lib\site-packages\tornado\stack_c
    ontext.py", line 315, in wrapped
            ret = fn(*args, **kwargs)
          File "C:\Program Files (x86)\Python36-32\lib\site-packages\tornado\simple_
    httpclient.py", line 395, in <lambda>
            lambda f: f.result())
          File "C:\Program Files (x86)\Python36-32\lib\site-packages\tornado\gen.py"
    , line 1113, in run
            yielded = self.gen.send(value)
          File "C:\Program Files (x86)\Python36-32\lib\site-packages\tornado\http1co
    nnection.py", line 186, in _read_message
            yield header_future
          File "C:\Program Files (x86)\Python36-32\lib\site-packages\tornado\http1co
    nnection.py", line 55, in __exit__
            raise _QuietException
        tornado.http1connection._QuietException
    [I 180625 16:57:05 web:2106] 200 GET http://www.baidu.com/ (127.0.0.1) 107.01ms

**Comment by ochen1** [comment]
我的fork把这个问题修好了：
https://github.com/ochen1/pyproxy/tree/patch-1
